version: "2"

linters:
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - cyclop
        - gocritic
        - revive
        - gosec
        - goconst
        - gocognit
